[package]
name = "openapiv3-extended"
version = "1.0.3"
authors = ["Kurt Wolf <kurtwolfbuilds@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
keywords = ["openapi", "v3"]
homepage = "https://github.com/kurtbuilds/openapiv3"
repository = "https://github.com/kurtbuilds/openapiv3"
description = "Fork of openapiv3 crate. Provides additional methods to simplify working with openapiv3 structs."

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
indexmap = {version = "1.0", features = ["serde-1"]}

[dev-dependencies]
newline-converter = "0.2.0"
serde_yaml = "0.8"

[features]
skip_serializing_defaults = []
